# Generated by Django 4.0.3 on 2022-05-16 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='categories_images')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Level',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('transcription', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
                ('example', models.TextField()),
                ('sound', models.FileField(upload_to='music')),
            ],
            options={
                'verbose_name_plural': 'Words',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='themes_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.category')),
                ('level', models.ManyToManyField(to='rest_api.level')),
                ('words', models.ManyToManyField(to='rest_api.words')),
            ],
            options={
                'verbose_name_plural': 'Themes',
            },
        ),
    ]
